### PR TITLE
Add dynamic libraries

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM

**Comment by SylvainCorlay** [comment]
I don't recall why this was not put in originally, but will fix whatever comes up.

I actually also need the dynamic library build of gtest.

**Comment by scopatz** [comment]
Do you want to hold off on this being merged until there are tests?

**Comment by SylvainCorlay** [comment]
I can add a test for existence of the dlls in the right place under sys prefix.

**Comment by scopatz** [comment]
That would probably be best :).  Just ping here when it is done!

**Comment by jakirkham** [comment]
> I don't recall why this was not put in originally, but will fix whatever comes up.

Maybe the reason can be found in these [builds](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.6978) or at least that is what I glean from this [comment](https://github.com/conda-forge/staged-recipes/pull/1564#issuecomment-247331439). Though I'm also unclear what went wrong.

> I actually also need the dynamic library build of gtest.

Seems like a good motivation. 😄 Also would be happy to have the dynamic libraries on all platforms. 👍

**Comment by SylvainCorlay** [comment]
Hum, I am seeing some memory errors in the appveyor logs. Earlier today, on a previous PR, builds randomly failed with a memory error on appveyor and restarting them fixed the issue.

**Comment by SylvainCorlay** [comment]
ok, restricting to the `gtest_dll` target seems to be doing the work.

**Comment by SylvainCorlay** [comment]
@scopatz this is ready. The dll part is built and placed in the correct location.

FYI, on my local build (I had a windows machine handy yesterday night), I had to be careful with the vcvarsall.bat incantation to have the dll part built with the right options (x64). I _think_ that this should already work out of the box on appveyor.

**Comment by SylvainCorlay** [comment]
I confirm that the conda-forge generated binary has the right x64 / x86 build depending on the plateform. 

Everything seems to be working!

**Pull request merged**
