### PR TITLE
Release install and add cmake installation

### LINKED ISSUE #8: Missing -D CMAKE_BUILD_TYPE=Release
It seems that gtest is being built in Debug mode.

### LINKED ISSUE #18: gtestTargets.cmake and gtestConfig.cmake missing
These files should be installed into `$PREFIX/lib/cmake/gtest` in order to simplify configuration of gtest as a dependency in cmake files.

### PR DESCRIPTION
**Pull request by kkraus14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #8 
Fixes #18

### CODE REVIEW

**Comment by kkraus14** [comment]
Unsure if this is the right approach to take regarding including the CMake installation files in both packages or if we should include it in only the `gtest` package.

Also not sure if this is the correct path for Windows.

**Comment by kkraus14** [comment]
Going to back out the Windows changes since Windows isn't actually running a CMake install step that would install the cmake configuration here.

**Comment by scopatz** [comment]
This looks good to me!

**Comment by scopatz** [comment]
Thanks @kkraus14

**Pull request merged**
