### PR TITLE
changes to also create debug binaries on Windows

### PR DESCRIPTION
**Pull request by giumas**
The output names are based on current CMake's FindGTest.cmake:
notepad _2018-03-10_12-45-03

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Thanks for doing this @giumas.

Generally including the debug libraries on Windows sounds like a good idea. It also seems like a good idea to have a build of the libraries with debug symbols on macOS and Linux as well. Admittedly this is done in a different way and would need to be handled differently.

That said, there has been a push to lighten packages in conda-forge as well. Expect that the solution will be to leverage conda-build 3's split packages. Raised issue ( https://github.com/conda-forge/conda-forge.github.io/issues/544 ) to discuss how we should do this. Would appreciate hearing from you over there.

**Comment by giumas** [comment]
@jakirkham I believe that having the debug libraries for `gtest` would be handy for debugging failing tests. The `gtest` conda package with debug libraries should not be too large in size compared with other packages.

**Comment by giumas** [comment]
@conda-forge-admin, please rerender.

**Comment by scopatz** [comment]
Is there a reason to not include the debugging libraries until we have more guidance? It seems like we can always split up the package later.

**Comment by giumas** [comment]
The last commit fixes https://github.com/conda-forge/gtest-feedstock/issues/20

**Pull request merged**
