### PR TITLE
Build with shared run-time library on Windows

### PR DESCRIPTION
**Pull request by maxhora**
Additional set of libraries built with dynamically linked Windows run-time library
[Issue request](https://github.com/conda-forge/gtest-feedstock/issues/13)

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I am worried that the renaming would prevent `find_package` to properly point the the right library?

**Comment by maxhora** [comment]
@SylvainCorlay , changes just add another set of libraries named with `_md` suffix. All previously built libraries remain untouched, so find_package hopefully will continue finding libraries without suffixes. I have created issue [here](https://github.com/conda-forge/gtest-feedstock/issues/13) to describe why libraries with dynamically linked run-time library are required.

**Comment by giumas** [comment]
@SylvainCorlay , can I advocate this @MaxRis 's PR?

**Comment by SylvainCorlay** [comment]
Sorry @MaxRis @giumas, this fell between the cracks. This should have been merged a very long time ago.

**Comment by SylvainCorlay** [comment]
Merging but with the recent issues with the anaconda tokens, this will probably only be added to the anaconda channel in a day or so.

**Comment by jakirkham** [comment]
IIUC the token issue is fixed for all feedstocks.

**Comment by giumas** [comment]
@SylvainCorlay , thank you! Should the build number be updated too?

**Comment by SylvainCorlay** [comment]
Sure, feel free to open a PR bumping the build number!

**Comment by maxhora** [comment]
@SylvainCorlay , @giumas thank you!

**Pull request merged**
