### PR TITLE
Add gmock to recipe

### LINKED ISSUE #31: Include gmock in this feedstock
I would like to get gmock into conda-forge.  It appears that google is now packaging gmock and gtest together (at least at source level).    Would it make sense to build the artifacts here or in a separate feedstock.  I can provide a PR to add it to this one if it is acceptable.

### PR DESCRIPTION
**Pull request by emkornfield**
WIP because I am still working on validating on windows (CI might not pass). Also I was able to build this with conda on ubuntu, but if there are any further tests I should do please let me know.

Fixes #31

Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering) (done by @xhochy)
* [ X] Ensured the license file is being packaged. (I see Packaged license file. in the logs)

### CODE REVIEW

**Comment by emkornfield** [comment]
OK builds seem to be working.  It looks like some unittests in python2.7 for windows failed to compile, I don't know if this indicates the library is unusable with MSVC 2008 or just those tests (couldn't get a local windows toolchain setup).

**Review by xhochy — APPROVED** [review]
This looks good. The branch was missing an update of the build number, just added that. Once the build passes, I think we can merge this.

**Comment by xhochy** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Thanks @emkornfield

**Pull request merged**
