### PR TITLE
Try using conda-build master

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/help-osx-arm64 The tests also now show that the signature is broken.

**Comment by erykoff** [comment]
A couple of things. One I don’t understand why we need this extra install of cctools here where we don’t need it anywhere else. Two, we shouldn’t run tests on arm64 on cross building. Three, the fake-signed with cctools/ldid binaries do fail validation via codesign but do work fine when run (that is they pass validation from the os.). I do not know what special bit isn’t set by the ldid program. 
That said, something can go wrong with our cctools that I think is related to reusing inodes that I’m looking into. And that may be an issue here, but running codesign isn’t a good test.

**Comment by xhochy** [comment]
> A couple of things. One I don’t understand why we need this extra install of cctools here where we don’t need it anywhere else. 

We otherwise would use the Xcode SDK's `install_name_tool` as its error messages says, invalidates the signature. Thus I was trying to use the 

> Two, we shouldn’t run tests on arm64 on cross building. 

These tests don't actually depend on arm64 executables but can also be run on systems that have the necessary tooling installed. We also did enable them on some other feedstocks.

> Three, the fake-signed with cctools/ldid binaries do fail validation via codesign but do work fine when run (that is they pass validation from the os.). I do not know what special bit isn’t set by the ldid program.


> That said, something can go wrong with our cctools that I think is related to reusing inodes that I’m looking into. And that may be an issue here, but running codesign isn’t a good test.

I did a bit of research and the only way you could check whether you have a valid fake `ldid` signature is whether a subsequent call to `ldid -S` modifies the binary. I wouldn't fully trust this though.

**Comment by erykoff** [comment]
Right.  The only surefire way that I know of to check if a signature is valid is to load a library/run a binary on an arm64 system.  This is less than ideal!

**Pull request closed without merging**
